"""
Django settings for learning_log project.

Generated by 'django-admin startproject' using Django 3.1.7.

For more information on this file, see
https://docs.djangoproject.com/en/3.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.1/ref/settings/
"""

from pathlib import Path
import os


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'ok)q(ion^xe)!os8(hieu^yxjwg$5jk(bxms%my+3y4x5sodk^'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    #第三方应用程序
    'bootstrap3',
    #my apps
    'learning_logs',#错误原因是没加逗号
    'users',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'learning_log.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates']
        ,
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],

},
    },
]

WSGI_APPLICATION = 'learning_log.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/3.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)python --version
# https://docs.djangoproject.com/en/3.1/howto/static-files/

STATIC_URL = '/static/'
#w我的设置
LOGIN_URL='/users/login/'
#django-bookstrap3的设置
BOOTSTRAP3={'include_jquery':True}
#Heroku设置
cwd=os.getcwd() #前面需要引入os
if cwd=='/app' or cwd[:4]=='/tmp':
    import dj_database_url
    DATABASES={
        'default':dj_database_url.config(default='postgres://localhost')
    }
    #让request.is_secure()承认X-Forwarded-Proto
    SECURE_PROXY_SSL_HEADER=('HTTP_X_FORWARDED_PROTO','https')
    #支持所有主机头（host header）
    ALLOWED_HOSTS = ['*']
    #静态资产配置
    BASE_DIR=os.path.dirname(os.path.abspath())
    STATIC_ROOT='staticfiles'
    STATICFILES_DIRS=(os.path.join(BASE_DIR,'static'))
#使用heroku local命令时会出现
#12:09:55 AM web.1 |  [2021-04-01 00:09:55 +0800] [41022] [ERROR] Retrying in 1 second.
#12:09:56 AM web.1 |  [2021-04-01 00:09:56 +0800] [41022] [ERROR] Connection in use: ('0.0.0.0', 5000)
#12:09:56 AM web.1 |  [2021-04-01 00:09:56 +0800] [41022] [ERROR] Retrying in 1 second.
#12:09:57 AM web.1 |  [2021-04-01 00:09:57 +0800] [41022] [ERROR] Connection in use: ('0.0.0.0', 5000)
#12:09:57 AM web.1 |  [2021-04-01 00:09:57 +0800] [41022] [ERROR] Retrying in 1 second.
#12:09:58 AM web.1 |  [2021-04-01 00:09:58 +0800] [41022] [ERROR] Connection in use: ('0.0.0.0', 5000)
#12:09:58 AM web.1 |  [2021-04-01 00:09:58 +0800] [41022] [ERROR] Retrying in 1 second.
#12:09:59 AM web.1 |  [2021-04-01 00:09:59 +0800] [41022] [ERROR] Connection in use: ('0.0.0.0', 5000)
#12:09:59 AM web.1 |  [2021-04-01 00:09:59 +0800] [41022] [ERROR] Retrying in 1 second.
#12:10:00 AM web.1 |  [2021-04-01 00:10:00 +0800] [41022] [ERROR] Can't connect to ('0.0.0.0', 5000)
#[DONE] Killing all processes with signal  SIGINT
#12:10:00 AM web.1 Exited with exit code null
#解决办法  kill `lsof -i :5000`
#之后再次输入 heroku local后出现
#12:18:03 AM web.1 |  [2021-04-01 00:18:03 +0800] [41107] [INFO] Starting gunicorn 20.1.0
#12:18:03 AM web.1 |  [2021-04-01 00:18:03 +0800] [41107] [INFO] Listening at: http://0.0.0.0:5000 (41107)
#12:18:03 AM web.1 |  [2021-04-01 00:18:03 +0800] [41107] [INFO] Using worker: sync
#12:18:03 AM web.1 |  [2021-04-01 00:18:03 +0800] [41108] [INFO] Booting worker with pid: 41108
